"""
MAGNETIC RESONANCE PLAYGROUND — residual neutrino magnetic moment in TGP
========================================================================

Pytanie: czy massive neutrino (n_winding=0) w TGP może mieć residualny
magnetic moment via motion-induced wake / nonlinear J_amp↔J_phase coupling?

Hipoteza:
  - Static n=0 kink: μ = 0 (no linear B coupling) — consistent with SM tree
  - Moving n=0 kink: wake δθ ≠ 0 → effective coupling to A_μ via |Φ|²·∂θ·A
  - RP² Berry phase spin-1/2 → angular momentum exists, can precess in B
  - Effective μ_ν^TGP from higher-order J_amp↔J_phase coupling

Compare with:
  - SM Dirac loop: μ_ν^SM ≈ 3·10⁻¹⁹ μ_B · (m_ν/eV)
  - XENONnT 2022: μ_ν < 6.3·10⁻¹² μ_B (experimental upper bound)
  - GEMMA: μ_ν < 2.9·10⁻¹¹ μ_B
  - Red giants: μ_ν < 3·10⁻¹² μ_B (astrophysical)

PRE-DISCLAIMER: To jest exploration, NIE cykl. Mechanism candidate, nie derivation.
"""

import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

import sympy as sp
from sympy import (
    Float, Rational, log, exp, sqrt, E, symbols, pi, simplify,
    diff, expand, I as imI, integrate, oo
)

print("="*84)
print("MAGNETIC RESONANCE PLAYGROUND — TGP neutrino μ_ν w light of mass m_ν > 0")
print("="*84)
print()

# =========================================================================
# Section 1: Substrate Lagrangian — Φ = |Φ|·exp(iθ) coupling do A_μ
# =========================================================================
print("SECTION 1 — Substrate Lagrangian z minimal coupling do A_μ")
print("-"*84)
print()

# Standard scalar QED Lagrangian:
# L = |D_μΦ|² - V(|Φ|),  D_μ = ∂_μ - ieA_μ
# Expanding Φ = |Φ|·exp(iθ):
# L = (∂|Φ|)² + |Φ|²(∂θ - eA)² - V(|Φ|)

# Symbolic variables
PhiMag, theta, A, e_coupl = symbols('|Φ| θ A_μ e', positive=True)
dPhi, dtheta = symbols('∂|Φ| ∂θ')
PhiMag_sym = symbols('|Φ|')

# Full kinetic term
L_kin = dPhi**2 + PhiMag_sym**2 * (dtheta - e_coupl*A)**2

print("Lagrangian density L_kin = (∂|Φ|)² + |Φ|²(∂θ - eA)² - V(|Φ|)")
print()
print(f"  L_kin (expanded) = {sp.expand(L_kin)}")
print()

# Expand the (∂θ - eA)² term explicitly
expanded = sp.expand(L_kin)
print("Terms breakdown:")
print(f"  (∂|Φ|)² ............ kinetic for |Φ| (J_amp sector)")
print(f"  |Φ|²·(∂θ)² ......... kinetic for θ (J_phase sector)")
print(f"  -2·e·|Φ|²·∂θ·A ..... LINEAR A coupling (electric current J^μ = -e·|Φ|²·∂^μθ)")
print(f"  e²·|Φ|²·A² ......... QUADRATIC A coupling (photon mass term, Higgs-like)")
print()


# =========================================================================
# Section 2: Static n=0 kink — μ = 0 at tree level
# =========================================================================
print("="*84)
print("SECTION 2 — Static n=0 kink: μ = 0 (tree level)")
print("="*84)
print()

# For n=0 kink: ∂θ = 0 statically (no phase winding around defect)
# Linear A coupling: -2e|Φ|²·∂θ·A = 0  (∂θ=0)
# Quadratic A coupling: e²|Φ|²·A² ≠ 0  (gives photon mass renormalization, not μ)

print("Dla static n_winding=0 kink:")
print("  ∂θ = 0 (no phase winding around defect)")
print()
print("  Linear coupling: J^μ = -e·|Φ|²·∂^μθ = 0")
print("    → no electric current → no electric charge → no magnetic moment at tree")
print()
print("  Quadratic coupling: e²·|Φ|²·A² ≠ 0 (gives local photon mass via Higgs mechanism)")
print("    → photon dispersion modification, NIE magnetic moment dipole linear w B")
print()
print("KONKLUZJA: μ_ν^TGP,tree = 0  (consistent z SM tree level)")
print()


# =========================================================================
# Section 3: Mechanism candidate A — Motion-induced wake (J_phase response)
# =========================================================================
print("="*84)
print("SECTION 3 — Motion-induced wake: δθ generated by moving kink")
print("="*84)
print()
print("Per MAG-resonance cycle (2026-05-09): kink poruszający się z v generuje")
print("δΦ-wake w substracie z motion-derived ω = v/λ_relevant.")
print()
print("Pytanie: czy wake zawiera δθ ≠ 0?")
print()
print("Heuristyka:")
print("  - Static kink (v=0): θ = const (no winding); ∂θ = 0")
print("  - Moving kink (v>0): kink 'zamiata' substrate; substrate response involves")
print("    BOTH amplitude (δ|Φ|) AND phase (δθ) components z linearyzowanej EOM")
print()

# Linearized EOM around vacuum: δ|Φ|, δθ
# Klein-Gordon for δ|Φ|: (∂²+m²_amp)·δ|Φ| = source (kink)
# K-G for δθ: ∂²·δθ = (1/|Φ_0|²)·∂_μJ^μ where J^μ is induced current

# For uniformly moving kink with mass m_ν at velocity v:
# Source for δ|Φ|: kink amplitude profile, time-dependent due to motion
# Source for δθ: from kink-substrate interaction; specifically from |Φ|²·(∂θ-eA)²
#                cross-term Φ_0·δ|Φ|·∂θ·A — but ∂θ_static=0 → no source unless A≠0

# In B field A≠0:
# Effective source for δθ via cross-term: ~ e · A · (δ|Φ|/|Φ_0|) · ∂_μ
# For moving kink in B field: δ|Φ| oscillates → effective δθ source proportional to v

print("W obecności A_μ (B field) i moving kink:")
print("  δθ source ∝ e·A·(δ|Φ|/|Φ_0|)·(v/c)")
print()
print("To znaczy: nawet n_winding_static = 0, w obecności B field i v ≠ 0,")
print("kink generuje effective δθ ≠ 0 — który następnie sprzęga się linearowo")
print("do A przez |Φ|²·∂θ·A term.")
print()
print("Efektywna 'phantom charge density': ρ_eff = -e·|Φ_0|²·∂_0(δθ)")
print("                                          ∝ e²·A·(δ|Φ|/|Φ_0|)·(v/c)·|Φ_0|²")
print("                                          ∝ e²·(δ|Φ|·|Φ_0|)·(v/c)·A")
print()


# =========================================================================
# Section 4: Heuristic estimate μ_ν^TGP
# =========================================================================
print("="*84)
print("SECTION 4 — Heurystyczna estimata μ_ν^TGP")
print("="*84)
print()

# Constants
mu_B_SI = 9.274e-24  # Bohr magneton J/T
m_e_eV = 0.5109989461e6  # electron mass in eV
hbar_eVs = 6.582e-16  # ℏ in eV·s
c_ms = 3e8  # m/s
alpha_em = 1/137.036

# TGP neutrino parameters (from previous playground)
m_nu_eV = 0.1  # 0.1 eV typical
g0_nu = 0.224  # from previous playground (g_0 of neutrino at m=0.1 eV)
A_tail_nu = 6.1e-4  # tail amplitude
A_tail_e = 0.110  # electron tail amplitude
g0_e = 0.86941

A_ratio = A_tail_nu / A_tail_e
g_ratio = g0_nu / g0_e

print(f"TGP neutrino params (m_ν = {m_nu_eV} eV from previous playground):")
print(f"  g_0_ν = {g0_nu}, A_tail_ν = {A_tail_nu:.2e}")
print(f"  A_tail_ν/A_tail_e = {A_ratio:.3e}")
print(f"  g_0_ν/g_0_e = {g_ratio:.3f}")
print()

print("Dimensional analysis kandidatów dla μ_ν^TGP:")
print()
print("  Bohr-like z m_ν: μ_eν_naive = eℏ/(2m_ν) = μ_B · (m_e/m_ν)")
m_ratio_e_nu = m_e_eV / m_nu_eV
mu_naive = m_ratio_e_nu  # in μ_B units
print(f"    = μ_B · {m_ratio_e_nu:.2e} (too large by ~10²⁰ vs experimental bound)")
print()

# Suppression scenarios
print("Suppression scenarios (varying coupling power n):")
print(f"  μ_ν^TGP / μ_B = (m_e/m_ν) · (A_tail_ν/A_tail_e)^n")
print()
print(f"  {'n':>4s} {'mu_ν/μ_B':>14s}  region")
print("  " + "-"*45)
for n in [0, 1, 2, 3, 4, 5, 6]:
    mu_ratio = m_ratio_e_nu * (A_ratio**n)
    region = ""
    if mu_ratio > 1:
        region = "TOO LARGE (μ_ν > μ_B unphysical)"
    elif mu_ratio > 1e-11:
        region = "RULED OUT by XENONnT (μ_ν < 6.3e-12 μ_B)"
    elif mu_ratio > 1e-19:
        region = "TESTABLE WINDOW (SM Dirac < μ_ν^TGP < experimental)"
    elif mu_ratio > 1e-20:
        region = "near SM Dirac loop prediction"
    else:
        region = "below SM Dirac loop (model-dependent)"
    print(f"  {n:>4d} {mu_ratio:>14.3e}  {region}")
print()

print("SM Dirac loop reference: μ_ν^SM = 3·10⁻¹⁹ μ_B · (m_ν/eV) = 3.0e-20 μ_B for m_ν=0.1 eV")
print("Experimental bound (XENONnT 2022): μ_ν < 6.3·10⁻¹² μ_B")
print()


# =========================================================================
# Section 5: Best-guess TGP scaling
# =========================================================================
print("="*84)
print("SECTION 5 — Best-guess TGP scaling argument")
print("="*84)
print()
print("Mechanism kandidat (TGP-native):")
print("  μ_ν^TGP ~ μ_B · (m_e/m_ν) · (A_tail_ν/A_tail_e)² · (v/c)²")
print()
print("Reasoning:")
print("  - Factor (m_e/m_ν): standard Bohr magneton scaling z mass")
print("  - Factor (A_tail)²: quadratic w amplitude (analog do Higgs term e²|Φ|²A²)")
print("  - Factor (v/c)²: motion suppression (Cherenkov-like, MAG-resonance ω_motion)")
print()

# Compute for different velocity scales
print("Estimates dla różnych prędkości:")
print()
print(f"  {'context':25s} {'v/c':>10s} {'mu_ν/μ_B':>14s}  comment")
print("  " + "-"*65)
scenarios_v = [
    ('thermal (CMB ν, ~ 2K)',  2e-4),     # CMB neutrino background
    ('solar ν (MeV scale)',     0.99999),  # relativistic
    ('reactor ν (MeV scale)',   0.99999),
    ('atmospheric (GeV)',       0.9999999),
    ('beta-decay endpoint',     0.1),     # KATRIN regime
    ('IceCube TeV ν',           1.0),     # ultra-relativistic
    ('rest frame (limit)',      1e-10),   # essentially at rest
]
for ctx, v_over_c in scenarios_v:
    mu_TGP_over_muB = m_ratio_e_nu * (A_ratio**2) * (v_over_c**2)
    region = ""
    if mu_TGP_over_muB > 6.3e-12:
        region = "RULED OUT"
    elif mu_TGP_over_muB > 3e-20:
        region = "OBSERVABLE WINDOW"
    else:
        region = "below SM Dirac loop"
    print(f"  {ctx:25s} {v_over_c:>10.4g} {mu_TGP_over_muB:>14.3e}  {region}")
print()

# Heuristic best estimate
mu_TGP_best = m_ratio_e_nu * (A_ratio**2) * (0.99**2)  # relativistic ν
print(f"Best heuristic (relativistic neutrino, v ~ c):")
print(f"  μ_ν^TGP ≈ {mu_TGP_best:.2e} μ_B")
print(f"  Status: ", end="")
if mu_TGP_best > 6.3e-12:
    print("RULED OUT by XENONnT — TGP scaling needs revision")
elif mu_TGP_best > 3e-20:
    print("WITHIN TESTABLE WINDOW — falsifiable by future experiments")
else:
    print("Below experimental sensitivity (consistent with SM Dirac)")
print()


# =========================================================================
# Section 6: Magnetic resonance signature
# =========================================================================
print("="*84)
print("SECTION 6 — Magnetic resonance: Larmor frequency w typical B fields")
print("="*84)
print()
print("Spin-1/2 z magnetic moment μ in B field: ω_Larmor = 2μB/ℏ")
print()
print(f"  {'B field source':35s} {'B [T]':>12s} {'ω_L [Hz]':>14s}  comment")
print("  " + "-"*72)
B_scenarios = [
    ('Earth (geomagnetic)',           5e-5),
    ('Laboratory standard',           1.0),
    ('High-field magnet (NMR/MRI)',   10.0),
    ('Strongest lab pulsed',          1000.0),    # 1 kT pulsed
    ('Magnetar surface',              1e11),     # 10¹¹ T
    ('Neutron star (typical)',        1e8),      # 10⁸ T
    ('Galactic (typical interstellar)', 1e-10),
]

# Use best estimate for μ_ν^TGP
mu_TGP_SI = mu_TGP_best * mu_B_SI  # convert to J/T
hbar_SI = 1.054e-34  # J·s

for ctx, B in B_scenarios:
    omega_L = 2 * mu_TGP_SI * B / hbar_SI
    period = 1/omega_L if omega_L > 0 else float('inf')
    if omega_L < 1e-3:
        comment = "too slow (< mHz)"
    elif omega_L < 1:
        comment = "low (mHz-Hz)"
    elif omega_L < 1e6:
        comment = "audio-RF"
    elif omega_L < 1e9:
        comment = "MHz-GHz radio"
    elif omega_L < 1e12:
        comment = "microwave"
    else:
        comment = "infrared/visible"
    print(f"  {ctx:35s} {B:>12.2e} {omega_L:>14.3e}  {comment}")
print()

print("Detection window analysis (μ_ν^TGP = {:.2e} μ_B):".format(mu_TGP_best))
print(f"  - W 1 T lab field: ω_L = {2*mu_TGP_SI*1.0/hbar_SI:.2e} Hz")
print(f"  - W 10 T NMR: ω_L = {2*mu_TGP_SI*10.0/hbar_SI:.2e} Hz")
print(f"  - W magnetar B=10¹¹ T: ω_L = {2*mu_TGP_SI*1e11/hbar_SI:.2e} Hz")
print()


# =========================================================================
# Section 7: Comparison summary
# =========================================================================
print("="*84)
print("SECTION 7 — μ_ν^TGP vs SM Dirac loop vs Experimental")
print("="*84)
print()

mu_SM_loop = 3e-19 * m_nu_eV  # 3·10⁻¹⁹ μ_B per (m_ν/eV)
mu_XENONnT = 6.3e-12  # XENONnT 2022 bound

print(f"For m_ν = {m_nu_eV} eV:")
print()
print(f"  SM Dirac loop prediction:   μ_ν^SM   = {mu_SM_loop:.2e} μ_B")
print(f"  TGP best estimate:          μ_ν^TGP  = {mu_TGP_best:.2e} μ_B")
print(f"  Experimental bound (XENONnT): μ_ν     < {mu_XENONnT:.2e} μ_B")
print()

ratio_TGP_SM = mu_TGP_best / mu_SM_loop if mu_SM_loop > 0 else float('inf')
print(f"  μ_ν^TGP / μ_ν^SM = {ratio_TGP_SM:.2e}  (TGP is {'larger' if ratio_TGP_SM > 1 else 'smaller'})")
print()

# log distance to bounds
import math
log_dist_to_XENON = math.log10(mu_XENONnT/mu_TGP_best) if mu_TGP_best > 0 else float('inf')
log_dist_to_SM = math.log10(mu_TGP_best/mu_SM_loop) if mu_SM_loop > 0 and mu_TGP_best > 0 else float('inf')
print(f"  Distance to XENONnT bound: {log_dist_to_XENON:.1f} orders of magnitude (above current sensitivity)")
print(f"  Distance to SM Dirac loop: {log_dist_to_SM:.1f} orders of magnitude (above SM tree+loop)")
print()


# =========================================================================
# Section 8: Open questions / hipotezy do dalszego testowania
# =========================================================================
print("="*84)
print("SECTION 8 — Otwarte pytania")
print("="*84)
print()
print("1. PROPER DERIVATION power n w (A_tail/A_e)^n:")
print("   - Wymaga full Feynman calculation z emergent Dirac S_F^TGP")
print("   - L08-Dirac-Wilson framework jest tu reusable")
print("   - Hipoteza: n=2 (quadratic w amplitude) z Higgs-mass-like cross-term")
print()
print("2. WAKE STRUCTURE moving n=0 kink:")
print("   - Czy δθ wake jest GENERATED dla pure translation?")
print("   - Lub wymagana jest spin (RP² Berry phase) coupling przez Larmor precession?")
print("   - MAG-resonance cycle's ω_motion adresuje to częściowo")
print()
print("3. ENHANCEMENT vs SUPPRESSION przez TGP topology:")
print("   - SM Dirac loop: μ_ν ~ (G_F·m_ν)/(8π²√2) — bardzo małe")
print("   - TGP heuristic: μ_ν ~ μ_B·(m_e/m_ν)·(A_tail)² — może być znacznie WIĘKSZE")
print("   - Jeśli prawdziwe, TGP przewiduje OBSERWABLE residual μ_ν w testowalnym oknie")
print()
print("4. ASTROFIZYCZNE konsekwencje:")
print("   - W silnym B field (magnetar, neutron star), znaczna ω_L → spin flip")
print("   - May affect neutrino transport w pulsarach / supernova")
print("   - Mogłoby dawać unique signature pulsar emission")
print()
print("5. CONNECTION DO neutrino oscillations:")
print("   - PMNS mixing matrix może być related do μ_ν via spin precession in cosmic B")
print("   - Solar neutrino problem solution: RSFP (Resonant Spin-Flavor Precession)")
print("   - Wymaga μ_ν > 10⁻¹² μ_B i magnetic field w Sun")
print("   - TGP-predicted μ_ν może być too small (or just right)")
print()


# =========================================================================
# Section 9: Heuristic prediction summary
# =========================================================================
print("="*84)
print("SECTION 9 — Heuristic prediction (subject to formal derivation)")
print("="*84)
print()
print(f"TGP-native estimate (subject to power assumption n=2):")
print(f"  μ_ν^TGP ≈ {mu_TGP_best:.2e} μ_B  (for m_ν = 0.1 eV, relativistic)")
print()
print(f"Scenario range (n=2 to n=6):")
mu_n2 = m_ratio_e_nu * A_ratio**2
mu_n4 = m_ratio_e_nu * A_ratio**4
mu_n6 = m_ratio_e_nu * A_ratio**6
print(f"  n=2: μ_ν^TGP = {mu_n2:.2e} μ_B  ← BEST GUESS")
print(f"  n=4: μ_ν^TGP = {mu_n4:.2e} μ_B")
print(f"  n=6: μ_ν^TGP = {mu_n6:.2e} μ_B  ← near SM prediction")
print()
print(f"FALSIFIABILITY:")
print(f"  • If μ_ν is measured > {6.3e-12:.1e} μ_B → either TGP n<2 or new physics beyond")
print(f"  • If μ_ν measured at 10⁻¹³ to 10⁻¹⁹ μ_B → TGP n=2-6 region — consistent")
print(f"  • If μ_ν < 10⁻²⁰ μ_B (very tight bound from astrophysics) → may rule out n=2")
print()
print(f"NEXT MEASUREMENTS:")
print(f"  • XLZD / DARWIN: μ_ν < 10⁻¹² μ_B target (next decade)")
print(f"  • Strongest astrophysical (red giant cooling): μ_ν < 3·10⁻¹² μ_B current")
print(f"  • Cosmological (BBN, CMB): μ_ν < 10⁻¹³ μ_B from neutrino decoupling effects")
print()

print("="*84)
print("END MAGNETIC RESONANCE PLAYGROUND")
print("="*84)
