"""
Lattice correction analysis for TGP BH soliton.

Question: Does the discrete substrate modify psi(r) = (1+3r_s/r)^{1/3}
enough to create a photon sphere?

Key result: The soliton is PROTECTED by harmonicity.
"""
import math

print("=" * 60)
print("THEOREM: HARMONICITY PROTECTION OF THE SOLITON")
print("=" * 60)
print()
print("The soliton u = 1 + C/r satisfies nabla^2 u = 0.")
print("The discrete Laplacian (Taylor) expansion is:")
print("  nabla^2_disc = nabla^2 + sum c_n L_B^{2n} nabla^{2(n+1)}")
print()
print("Since nabla^{2k} u = 0 for all k >= 1 (harmonic function),")
print("ALL perturbative lattice corrections vanish identically.")
print()
print("=> psi = (1 + 3r_s/r)^{1/3} is an EXACT solution of the")
print("   lattice-corrected equation to ALL orders in L_B.")
print()
print("=" * 60)
print("NON-PERTURBATIVE BREAKDOWN SCALE")
print("=" * 60)
print()
print("Taylor expansion of nabla^2_disc breaks when field varies")
print("on scales comparable to L_B. For the soliton near center:")
print("  |psi'| * L_B / psi ~ r_s * L_B / (3 r^2)")
print("Breakdown when r ~ sqrt(r_s * L_B / 3)")
print()

r_s_val = 1e4  # stellar BH in meters
print(f"Stellar BH: r_s = {r_s_val:.0e} m")
print(f"Photon sphere would be at r ~ r_s = {r_s_val:.0e} m")
print()
for lb_exp in [-35, -20, -10, 0, 10]:
    lb = 10**lb_exp
    r_break = math.sqrt(r_s_val * lb / 3)
    ratio = r_break / r_s_val
    print(f"  L_B = 1e{lb_exp:+d} m  =>  r_break = {r_break:.2e} m  "
          f"(r_break/r_s = {ratio:.2e})")

print()
print(f"Planck lattice (L_B = 1.6e-35 m):")
r_break = math.sqrt(r_s_val * 1.6e-35 / 3)
print(f"  r_break = {r_break:.2e} m  (sub-Planckian!)")
print()

print("=" * 60)
print("WHAT ABOUT THE FULL NONLINEAR KINETIC OPERATOR?")
print("=" * 60)
print()
print("The TGP equation is NOT nabla^2 u = 0 on the lattice.")
print("It is: nabla^2_disc(psi^3) = 0, where psi^3 = u.")
print()
print("On a discrete lattice, psi^3 is evaluated at lattice sites:")
print("  psi(x_i)^3 = (Phi_i / Phi_0)^3")
print()
print("The key point: u = psi^3 is STILL harmonic.")
print("The lattice equation is: sum_neighbors [u(x+L_B e)] - 2d u(x) = 0")
print("This is the discrete harmonic equation.")
print()
print("Does u = 1 + C/r solve the EXACT discrete harmonic equation")
print("(not just the Taylor approximation)?")
print()
print("NO! The discrete harmonic equation on a cubic lattice is:")
print("  u(x+a,y,z) + u(x-a,y,z) + u(x,y+a,z) + u(x,y-a,z)")
print("  + u(x,y,z+a) + u(x,y,z-a) - 6 u(x,y,z) = 0")
print()
print("The function 1/r is NOT an exact discrete harmonic function!")
print("The discrete Green's function G_disc(x) differs from 1/(4 pi r)")
print("at short distances r ~ L_B.")
print()
print("=" * 60)
print("DISCRETE GREEN'S FUNCTION")
print("=" * 60)
print()
print("On a 3D cubic lattice with spacing a, the lattice Green's function")
print("G(n1,n2,n3) satisfies:")
print("  sum_neighbors G - 6G = -delta_{n,0}")
print()
print("Asymptotically: G ~ 1/(4 pi a |n|) for |n| >> 1")
print("Near origin: G(0,0,0) = 1/(6 * 2 pi^2) * integral = 0.2527/a")
print("  (Watson's triple integral)")
print()
print("The lattice Green's function is FINITE at the origin!")
print("Continuum 1/r diverges, but discrete G(0) is finite.")
print()

# Watson's triple integral value
W = 0.505462  # Watson integral W_3 = 1/(4*pi^3) * triple integral
G0_over_a = W / (2 * math.pi)  # approximate
print(f"G_disc(0) ~ {G0_over_a:.4f} / a  (finite!)")
print()
print("This means: on the discrete lattice, u = 1 + C * G_disc(r)")
print("where G_disc(0) is FINITE, not divergent.")
print()
print("=> psi^3 = 1 + C * G_disc(r) is BOUNDED at r=0")
print("=> psi(0) is FINITE (not infinite)")
print("=> Frozen interior is replaced by a FINITE core")
print()

print("=" * 60)
print("IMPLICATIONS FOR PHOTON SPHERE")
print("=" * 60)
print()
print("In the continuum: psi(0) -> inf, h(0+) -> 0, h monotonic -> no PS")
print()
print("On the lattice: psi_max = (1 + C/a * G_disc_ratio)^{1/3} = FINITE")
print("  h(r) = r * psi(r)")
print("  h(0) = 0 (origin)")
print("  h(r_s) ~ r_s * (1+3)^{1/3} ~ 1.59 r_s")
print("  h(inf) -> inf")
print()
print("The question: does psi(r) grow fast enough near r=0 that")
print("h(r) = r * psi(r) overshoots, creating a local maximum?")
print()
print("For this we need h'(r_*) = 0 at some r_*:")
print("  h' = psi + r*psi' = 0  =>  psi'/psi = -1/r")
print()
print("In continuum: psi'/psi = -r_s/(r(r+3r_s)) -> -1/(3r) near r=0")
print("  Need -1/(3r) = -1/r => impossible (1/3 != 1)")
print()
print("On lattice: psi(r) flattens to psi_max for r < L_B")
print("  => psi' ~ 0 near r=0 => h' ~ psi > 0 => STILL no PS")
print()
print("The lattice REGULARIZES the divergence but makes the photon")
print("sphere condition HARDER to satisfy (psi' vanishes at center).")
print()

print("=" * 60)
print("FINAL VERDICT")
print("=" * 60)
print()
print("1. Perturbative lattice corrections: VANISH (harmonicity)")
print("2. Non-perturbative (discrete Green's function):")
print("   - Regularizes psi(0) to finite value")
print("   - Makes psi flatter near center")
print("   - h(r) = r*psi(r) STILL monotonically increasing")
print("3. NO PHOTON SPHERE even with discrete substrate")
print()
print("The no-photon-sphere result is ROBUST.")
print("Kill-shot K-H stands: ngEHT photon ring => TGP falsified.")
